### ISSUE TITLE
named scratchpads launched within its own cgroup?

### ISSUE THREAD

**Issue by kisonecat** [kanashimia/nixos-config#2]
I really like how you've set up xmonad to launch stuff in its own cgroup, which will hopefully address some of the issues with oom.

I'm looking at https://github.com/kanashimia/nixos/blob/e2931ba7c3e59392b73085f7b6e04197a8df8831/modules/window-managers/xmonad/xmonad.hs#L20-L26 and wondering if this launches Chromium in its own cgroup?  It seems like that would require patching runApplication in XMonad.Util.NamedScratchpad.

**Comment by kanashimia** [comment]
Yeah it wont, when i added scratchpads i saw that i would basically need to copypaste half of the module, just because i can't change `runApplication` (this happens alot of times with xmonad-contrib sadly)

Right now config looks like a mess, i'll look into actually doing something with it.

**Comment by kanashimia** [comment]
Ok, so i made separate library that has everything related, named scratchpads are there: https://github.com/kanashimia/xmonad-systemd
API of course won't be stable, and i don't plan to upload it to hackage.
My config now uses it.

(it would be nice to do something in the xmonad-contrib itself, but honestly i don't care enough to do it)
